# Generated by Django 5.2 on 2025-04-13 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('album_type', models.CharField(max_length=50)),
                ('total_tracks', models.IntegerField()),
                ('release_date', models.CharField(max_length=20)),
                ('release_date_precision', models.CharField(max_length=10)),
                ('href', models.URLField()),
                ('uri', models.CharField(max_length=100)),
                ('external_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('href', models.URLField()),
                ('uri', models.CharField(max_length=100)),
                ('external_url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='track',
            name='playlist',
        ),
        migrations.AddField(
            model_name='track',
            name='disc_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='explicit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='href',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='is_local',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='is_playable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='track',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='track_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='track',
            name='popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='uri',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='recommender.album'),
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(related_name='albums', to='recommender.artist'),
        ),
        migrations.AddField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(related_name='tracks', to='recommender.artist'),
        ),
        migrations.CreateModel(
            name='AvailableMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=10)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_markets', to='recommender.album')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_markets', to='recommender.track')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isrc', models.CharField(blank=True, max_length=50, null=True)),
                ('ean', models.CharField(blank=True, max_length=50, null=True)),
                ('upc', models.CharField(blank=True, max_length=50, null=True)),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='recommender.track')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recommender.album')),
            ],
        ),
    ]
